### ISSUE TITLE
Question: Raffle formula

### ISSUE THREAD

**Issue by cunningrat** [Grauenwolf/TravellerTools#100]
Can you please let me know what is the formula behind the "Raffle" checkbox in the trade generator?

**Comment by Grauenwolf** [comment]
Imagine that you had a box of raffle tickets. You give some tickets to each type of good:

- Goods with *: Always available
- Good with no mark: Only 1 chance
- Other goods: 5 chances plus 20 chances per matching remark (trade code)

The 6 raffle tickets are selected (drawing another ticket if the same good is chosen more than once).

****

For non raffle mode the rule is:

- Goods with *: Always available
- Matching Trade remarks: Always available
- Other goods: Randomly choose 1d6 goods

**Comment by Grauenwolf** [comment]
If you read C# code, look for line 190.

https://github.com/Grauenwolf/TravellerTools/blob/blazor/TravellerTools/Grauenwolf.TravellerTools.TradeCalculator/TradeEngine.cs
