### ISSUE TITLE
Traveller Map integration

### ISSUE THREAD

**Issue by flyteach** [Grauenwolf/TravellerTools#108]
Seems like something may have changed in someone's API, but it appears that unofficial sectors are no longer supported in either the stable version or the demo for v2. I know this was working about 6 months ago when I last checked (summer, work) and now it's getting cold out and I'm back to world (sector) building.

Thanks for a great tool, hope this gets resolved. FWIW, the sector I'm working with is Virgo Sector on TravellerMaps.

Thanks!
Jim

**Comment by Grauenwolf** [comment]
I finally found the problem. The Resource Units are coming in blank for systems in that sector, which I wasn't expecting.

Now if I can only remember how to update the website with the new code...

**Comment by Grauenwolf** [comment]
Done!
