### ISSUE TITLE
Subsector dropdown not populating

### ISSUE THREAD

**Issue by BrainPunter** [Grauenwolf/TravellerTools#109]
Hi there - am interested in trying out this tool for my Traveller campaign. However, when I load the page up and select a sector, nothing populates into the subsector dropdown.

I'm still able to pop UWPs into the other fields and generate info that way, though.

**Comment by Grauenwolf** [comment]
Thank you for letting me know. It looks like both versions of the site are down so so probably a change in Traveler Map broke it.

I'll try to look at it after work today.

**Comment by Grauenwolf** [comment]
Fixed in both versions.

https://travellertoolsdemo.azurewebsites.net/
http://travellertools.azurewebsites.net/

As I suspected, Traveller Tools did change their program. Fortunately it was easy enough to update ours to match.

**Comment by BrainPunter** [comment]
Awesome - thanks for fixing it, and thanks for developing the tool. It's great!

**Comment by Grauenwolf** [comment]
You're welcome. And thank you again for taking the time to let me know it was broken. It really helps.
