### ISSUE TITLE
Feature request: Buttons allowing opening in another tab/window

### ISSUE THREAD

**Issue by joeyeti** [Grauenwolf/TravellerTools#122]
Buttons in the apps are not created in a way as to allow opening the result in a new window (unlike links, say individual Characters). Could this be changed, so that the user does not need to redo the selections when examining a result and going back to the page?

**Comment by Grauenwolf** [comment]
Please add a link to the page you're concerned with.

**Comment by joeyeti** [comment]
For instance Galaxy Info, when I narrow the selections down to a Planet (and clicking on Planet Info), it shows the Planet Info. But going back resets all the dropdowns. The same for Characters or Contacts. I am using Firefox 115.5.

**Comment by Grauenwolf** [comment]
Oh sure, that should be easy enough. 

ref: https://travellertoolsdemo.azurewebsites.net/world

**Comment by Grauenwolf** [comment]
Done!

**Comment by joeyeti** [comment]
Works now, thx!
EDIT: Now if you can just add such to the other pages :)

**Comment by Grauenwolf** [comment]
No problem. I thought the buttons were ugly and was plenty on replacing them eventually anyways.

The next challenge is to get the back button work so it doesn't clear out the drop-downs. But I'm not at UI developer so this is going to take some research.

**Comment by joeyeti** [comment]
Thx and keep it up!
