### ISSUE TITLE
Store page Availability Target Summary

### ISSUE THREAD

**Issue by pelwer1** [Grauenwolf/TravellerTools#123]
For the Store page, would it be possible to also print out a few tables of Availability Targets for the various gear types? E.g. Tools: TL6 = 8; TL 7 = 9; ...

Would provide GM's a succinct table they could throw in their notes.

**Comment by Grauenwolf** [comment]
Done. https://travellertoolsdemo.azurewebsites.net/world/M1105/-4,-1/2036/store

**Comment by pelwer1** [comment]
Thank you!






Thanks,
Pat.

A little nonsense, now and then, is relished by the wisest men.  - Willy
Wonka
