### ISSUE TITLE
Psionics for Character Creator

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/TravellerTools#20]

**Comment by robertfreeborn** [comment]
I'm using Psionics in my MgT1e game.  So this would be appreciated.

**Comment by robertfreeborn** [comment]
I'm using Psionics in my MgT1e game. So this would be appreciated.

**Comment by robertfreeborn** [comment]
I'm using Psionics in my MgT1e game. So this would be appreciated.

**Comment by robertfreeborn** [comment]
I'm using Psionics in my MgT1e game. So this would be appreciated.

**Comment by Grauenwolf** [comment]
The character creator is currently designed for 2e. That generally isn't a problem for NPCs, but I'll need to see how much psionics changed.

But yea, I'll put at the top of my to-do list for Traveller Tools.

**Comment by Grauenwolf** [comment]
Done. It will now generate psionic characters.

**Comment by Grauenwolf** [comment]
Example: http://travellertools.azurewebsites.net/Home/Character?Career=Wild+Talent

**Comment by robertfreeborn** [comment]
I tested the new Psion careers as well as the very rare life event for finding an institute.  Works like a charm! Very nice.  Thank you!

**Comment by Grauenwolf** [comment]
You're welcome. And thank you for testing; that helps a lot.
