### ISSUE TITLE
Custom UWPs for trade tables

### ISSUE THREAD

**Issue by SpamIam18** [Grauenwolf/TravellerTools#24]
Have the ability to enter in a UWP for the current location and destination world, enter in the distance and have it generate freight, passengers, mail, trade tables, et.

**Comment by BigDogsRunning** [comment]
Great idea. The suggestion says it all. I don't have anything to add.

**Comment by Grauenwolf** [comment]
Done!

**Comment by BigDogsRunning** [comment]
All I have to say is, Amazeballs! 😊

Thank you very much for this.

**Comment by Grauenwolf** [comment]
You're welcome. Sorry I forgot about it for so long.
