### ISSUE TITLE
Allow milieu selection when pulling data from TravellerMap

### ISSUE THREAD

**Issue by inexorabletash** [Grauenwolf/TravellerTools#25]
TravellerMap.com now supports multiple milieu. As noted here:

http://www.travellerrpg.com/CotI/Discuss/showpost.php?p=560659&postcount=7

This is not supported with TravellerTools.

You can see one way to do this with the utility used by the various "maker" pages:

https://github.com/inexorabletash/travellermap/blob/master/make/post.js#L26

... and then pass `milieu` along as an option on various queries, e.g.:

https://github.com/inexorabletash/travellermap/blob/master/make/post.js#L44

**Comment by kilgs** [comment]
Thanks, Tash. 
Grauenwolf, this came from a request by me to include the "Gateway To Destiny" UWP's to the TravellerMap so it could be accessed through your application. Inexorabletash pointed out that the Experimental option on the TravMap already has all of the data in it... just not on the main map. 
I have no idea of the complexity but it would sure get me to the finish line on a Glimmerdrift campaign set in the 990's!
Thanks to both of you for some excellent tools that allow non-codies to maximize their Traveller experience!

**Comment by Grauenwolf** [comment]
Doesn't sound hard. No promises, but I'll try to look at it this weekend.

**Comment by Grauenwolf** [comment]
Done!

**Comment by kilgs** [comment]
Oh snap... you just made my fricking year! Thank you!
    On Monday, October 30, 2017, 4:29:02 AM CDT, Jonathan Allen <notifications@github.com> wrote:  
 
 
Closed #25.

**Comment by Grauenwolf** [comment]
You're welcome. Sorry it took so long, I got distracted by other projects.

**Comment by kilgs** [comment]
No worries at all. Your volunteerism shames me as I have no tech talents.
    On Tuesday, October 31, 2017, 10:21:11 AM CDT, Jonathan Allen <notifications@github.com> wrote:  
 
 
You're welcome. Sorry it took so long, I got distracted by other projects.

**Comment by Grauenwolf** [comment]
Just keeping your eyes open for ways to make this better helps a lot.
