### ISSUE TITLE
Names of goods for MGT2

### ISSUE THREAD

**Issue by Kulthea** [Grauenwolf/TravellerTools#28]
The trade goods listed are not the same as those listed in MGT2 core book (pages 212-213) even when Mongoose 2 is selected. Basic goods are now "common" etc.

**Comment by Grauenwolf** [comment]
Here's the trade goods file for MGT2. 

https://raw.githubusercontent.com/Grauenwolf/TravellerTools/master/TravellerTools/Grauenwolf.TravellerTools.Web/App_Data/TradeGoods-MGT2.xml

Please update it as you see fit and send it back to me.

**Comment by Kulthea** [comment]
Hi,

Here’s the updated MGT2 trade goods list.

I’ve put in the Tons as “1D6x10” and so on. Not sure how to do the multiplier but the new rules are clear it’s 1D6x10 and not 10d6.

Also I’ve removed the detail rolls as those are not provided in MGT2 which simplifies things a lot IMO.

Matt

**Comment by Kulthea** [comment]
I've zipped and attached file.
[TradeGoods-MGT2.zip](https://github.com/Grauenwolf/TravellerTools/files/1426442/TradeGoods-MGT2.zip)

**Comment by Grauenwolf** [comment]
We need the detail rolls because some people are using MGT2 with the old MGT1 Merchant Prince rules. (The detail rolls are ignored unless you check the "Advanced" box.)

It doesn't currently support "1d6 x 10". The closest you can get it "10d6".

**Comment by Kulthea** [comment]
Advanced mode. Fair enough. Some tweaking of quantities or prices might be in order, but would work.

Is there scope to add a multiplier field so 1d6 x10 is split into Amount="1D" and Multiplier="10". ? Otherwise there is always around 35 tons rather than equal chances of 10 or 60.

I like the raffle option but trade codes (e.g. high tech always has Advanced items) is not working last time I looked.

Matt

On 30 Oct 2017, at 8:37 pm, Jonathan Allen <notifications@github.com<mailto:notifications@github.com>> wrote:


We need the detail rolls because some people are using MGT2 with the old MGT1 Merchant Prince rules. (The detail rolls are ignored unless you check the "Advanced" box.)

It doesn't currently support "1d6 x 10". The closest you can get it "10d6".

-

**Comment by Grauenwolf** [comment]
My apologies, it seems that this got forgotten. 

It is now fixed in Traveller Tools II. https://travellertoolsdemo.azurewebsites.net/
