### ISSUE TITLE
Fails to parse placeholder entries

### ISSUE THREAD

**Issue by inexorabletash** [Grauenwolf/TravellerTools#31]
TravellerMap has some placeholder entries in sector data, e.g. worlds with UWPs like `???????-?`. These occur in Foreven (ref's preserve), several Aslan sectors, and for "anomalies" in Afawahisa, Reft, Corridor and Touchstone.

When such a sector is selected, the this API call fails:

`http://travellertools.azurewebsites.net/WorldApi/Subsectors?sectorCoordinates=-5,1&milieu=M1105` produces `500 Internal Server Error`

... which results in the site showing an empty subsector/world list.

**Comment by Grauenwolf** [comment]
Fixed. Thank you for discovering the problem.
