### ISSUE TITLE
Trade calculator...toggle for 'Red Zone'

### ISSUE THREAD

**Issue by rerednaweht** [Grauenwolf/TravellerTools#36]
FYI the tool is quite excellent.

As I was going through it I was unable to find a toggle for 'red zone'. This isn't part of a world UWP so isn't normally considered.  I would suggest adding it to the section where you have the options for Allow Illegal Goods. 

Thanks!

**Comment by Grauenwolf** [comment]
Ugh, forgot to mention that this is done.
