### ISSUE TITLE
Trade tables

### ISSUE THREAD

**Issue by jamesfoxbr** [Grauenwolf/TravellerTools#42]
My player found **Pharmaceuticals** and **Petrochemicals** have a Trade code of +1 when looking in **water worlds** like Torpol for example in my campaign. The book bonus for water world is 0.

**Comment by Grauenwolf** [comment]
Are you using Mongoose 1 or 2?

**Comment by jamesfoxbr** [comment]
I'm using Mongoose 2

**Comment by Grauenwolf** [comment]
My apologies, this got forgotten. It has been fixed in Traveller Tools II https://travellertoolsdemo.azurewebsites.net/
