### ISSUE TITLE
Choose Male/female Name for NPC generator

### ISSUE THREAD

**Issue by TheAlaine** [Grauenwolf/TravellerTools#43]
Sometimes you want a specific sex for an NPC, like an Stewardess.
Can you make a little Box to choose Mail/female/random names?
Great Tool btw thanks for making this!

**Comment by Grauenwolf** [comment]
Done.  https://travellertoolsdemo.azurewebsites.net/character

**Comment by Grauenwolf** [comment]
Fixed in Traveller Tools II: https://travellertoolsdemo.azurewebsites.net/character
