### ISSUE TITLE
[BUG] Trade Calculator return an error.

### ISSUE THREAD

**Issue by Grummore** [Grauenwolf/TravellerTools#45]
Error.
An error occurred while processing your request.

**Comment by Grauenwolf** [comment]
Please paste in the URL of the page

**Comment by Grummore** [comment]
http://travellertools.azurewebsites.net/Home/Character?minAge=&maxAge=&firstAssignment=Engineer/Gunner&finalCareer=Navy&finalAssignment=Engineer/Gunner

**Comment by Grummore** [comment]
It's the link it gives when I click on "Generate Trade info".

**Comment by Grauenwolf** [comment]
Did you pick a planet first?

**Comment by Grummore** [comment]
Dumb me. I didn't think they were connected (Location, Character and Trade).

**Comment by Grauenwolf** [comment]
It's a common mistake, meaning I need to clean up the UI.

**Comment by Grauenwolf** [comment]
No longer applicable, the new version doesn't have this flaw.
