### ISSUE TITLE
Adding Items to the DB

### ISSUE THREAD

**Issue by Pantsorama** [Grauenwolf/TravellerTools#47]
I'd like to add items to the shopping list.  This would allow items from sourcebooks to be available to travellers.

**Comment by Grauenwolf** [comment]
The way that works now is there's just a big file that we modify. 

https://github.com/Grauenwolf/TravellerTools/blob/master/TravellerTools/Grauenwolf.TravellerTools.Web/App_Data/Equipment.xml

You'll have to add your changes to it, then send it to me.
