### ISSUE TITLE
Permalinks not working at all

### ISSUE THREAD

**Issue by MusicManiac** [Grauenwolf/TravellerTools#50]
When you try to generate permalink by pressing "permalink", it opens page that doesn't exist.

> Error.
An error occurred while processing your request.

**Comment by Grauenwolf** [comment]
I need the URL you started on and the one that didn't work.

**Comment by MusicManiac** [comment]
Started here -> `http://travellertools.azurewebsites.net/`
Selected 1105 Milieu, changed Origin UWP to E4367BA6, pressed "Generate Trade Info", everything works, it opens following link: `http://travellertools.azurewebsites.net/Home/QuickTradeInfo?originUwp=E4367BA6&destinationUwp=&jumpDistance=1&brokerScore=0&advancedMode=false&illegalGoods=false&edition=2016&advancedCharacters=false&streetwiseScore=0&raffle=false&milieu=M1105&originTasZone=Green&destinationTasZone=Green`
It shows everything correctly. There is a big "Permalink" right at the top of the page. It forwards to `http://travellertools.azurewebsites.net/Home/TradeInfo?sectorX=0&sectorY=0&hexX=&hexY=&maxJumpDistance=0&brokerScore=0&advancedMode=False&illegalGoods=False&edition=Mongoose2&seed=377004684&advancedCharacters=False&streetwiseScore=0&milieu=M1105`
and I get 
![image](https://user-images.githubusercontent.com/14209235/78752699-d5e5dd00-7974-11ea-8d25-88f91b78a364.png)

**Comment by Grauenwolf** [comment]
Ah, that makes sense. I never tested permalink with manually entered planet codes. 

Should be an easy fix, but I don't know when I'll have a chance to do it. (Recently moved so I don't have a lot of free time.)

**Comment by MusicManiac** [comment]
Amazing tool, thanks for your work. Hope to see cool updates in the future :)

**Comment by xdy** [comment]
I just submitted a PR (https://github.com/Grauenwolf/TravellerTools/pull/57) that should fix this issue.
