### ISSUE TITLE
Pages not rendering correctly and trade calculator broken

### ISSUE THREAD

**Issue by simonjgreen** [Grauenwolf/TravellerTools#60]
Since the update a few days ago pages are not rendering correctly (possibly missing white space?) and importantly the Trade Calculator is now erroring with just "An error occurred while processing your request." 

Verifiable on your demo install [here](https://travellertools.azurewebsites.net/Home/QuickTradeInfo?originUwp=C300510-C&destinationUwp=C300510-C&jumpDistance=2&brokerScore=1&advancedMode=true&illegalGoods=false&edition=2016&advancedCharacters=true&streetwiseScore=2&raffle=true&milieu=M1105&originTasZone=Green&destinationTasZone=Green).

**Comment by Grauenwolf** [comment]
Sorry about that. It looked fine when I tested it because it had cached some of the old files and some of the new, putting it in a weird state.

**Comment by Grauenwolf** [comment]
Formatting is fixed. That one was on me. (Though I am annoyed that updating bootstrap broke it and the browser's caching hid that fact from me.)

@xdy When you renamed `jumpDistance` to `maxJumpDistance` you missed a spot in index.ts::GenerateTradeInfo. 

Both are fixed now.


https://travellertools.azurewebsites.net/Home/QuickTradeInfo?originUwp=C300510A&destinationUwp=C300510A&maxJumpDistance=2&brokerScore=0&advancedMode=false&illegalGoods=false&edition=2016&advancedCharacters=false&streetwiseScore=0&raffle=false&milieu=M1105&originTasZone=Green&destinationTasZone=Green

    if (originUwp != null && originUwp.length > 0) {
        window.location.href = "/Home/QuickTradeInfo?originUwp=" + originUwp + "&destinationUwp=" + destinationUwp + "&jumpDistance=" + jumpDistance + "&brokerScore=" + brokerScore + "&advancedMode=" + am + "&illegalGoods=" + ig + "&edition=" + edition + "&advancedCharacters=" + ac + "&streetwiseScore=" + streetwiseScore + "&raffle=" + raffle + "&milieu=" + milieu + "&originTasZone=" + originTasZone + "&destinationTasZone=" + destinationTasZone;
    }
    else {
        window.location.href = "/Home/TradeInfo?sectorX=" + a[0] + "&sectorY=" + a[1] + "&hexX=" + b + "&hexY=" + c + "&maxJumpDistance=" + maxJumpDistance + "&brokerScore=" + brokerScore + "&advancedMode=" + am + "&illegalGoods=" + ig + "&edition=" + edition + "&advancedCharacters=" + ac + "&streetwiseScore=" + streetwiseScore + "&raffle=" + raffle + "&milieu=" + milieu;
    }

**Comment by simonjgreen** [comment]
That was quick, thanks @Grauenwolf :)

**Comment by xdy** [comment]
Oh, bother. Thanks for fixing that @Grauenwolf !

**Comment by Grauenwolf** [comment]
I think I'm going to rewrite the website in Blazor. I'm tired of fighting with stupid stuff like these two bugs. 

I just finished the conversion for another project and it turned out well. https://savagetoolsweb.azurewebsites.net

For that one I kept most of the old code, so I'm hopeful Traveller will be just as easy.

**Comment by xdy** [comment]
Awesome. Especially as I was looking for an excuse to take a look at Blazor anyway. :)
