### ISSUE TITLE
Passengers

### ISSUE THREAD

**Issue by jcdj** [Grauenwolf/TravellerTools#65]
Hi, 
When you use the trade calculator, does it also calculates the passengers and their modifiers or just generates random characters? And does streetwise and broker dm counts or thats just for trade ?

Ty

**Comment by Grauenwolf** [comment]
Under Mongoose 2nd edition rules, the highest Steward skill for the crew is supposed to affect passenger counts. 

Also the result of a Broker, Streetwise, or Carouse roll.

Currently neither of these are included, but it's something to consider for the new version.

**Comment by jcdj** [comment]
Ty, I'm eager to see the new version, I close the issue.
