### ISSUE TITLE
Feature request: destination view should display desired/available freights

### ISSUE THREAD

**Issue by IvanSanchez** [Grauenwolf/TravellerTools#70]
In my campaign, we use to **compare** the available freight types at an origin world, and the desired freight types at the destination world. We take the DMs, then use a VTT to make the actual rolls so that everyone sees the rolls at the same time.

So, when planning a jump from a world to another world (which I guess it's the "destination" view given the URL fragment) *ideally*, I'd like to have a table of trade goods that:
- Displays all goods *either* available at origin *or* desired at destination
   - Displays purchase DMs for freights available and sell DMs for freights desired
- *Highlights* goods available at origin *and* desired at destination
   - Displays expected profit margin (%) and profit per ton
   - Tiny bit of javascript to re-calculate profits based on Broker skill DM
- Does *not* automatically do any Broker rolls
   - This would keep the information cacheable and archiveable
   - A bit of Javascript could be added to actually make rolls when needed, even asking for the Broker skill DM

**Comment by Grauenwolf** [comment]
Destination DMs are now available on the **Trade** page.

https://travellertoolsdemo.azurewebsites.net/world/M1105/-4,-1/0705/trade

**Comment by Grauenwolf** [comment]
Estimated profit margin is now included when you pick a destination. 

You also have the ability to skip the broker roll.
