### ISSUE TITLE
Extend available and desired goods to include sale DM in adjacent systems

### ISSUE THREAD

**Issue by markawstewart** [Grauenwolf/TravellerTools#72]
In determining which goods to buy the sale DM for adjacent systems is useful to factor in.

A mechanism for displaying this information for the available (and possibly desired) goods display is useful.

Two mechanism suggest themselves.
1) extend the tables to include the sale DM for all systems within jump distance.
2) repeat the table for each system in jump distance and include the sale DM for that system.

**Comment by Grauenwolf** [comment]
I don't like either of those, but there is something I can do for you. In the new Trade screen, we can have a "Show Desired Goods" drop-down that lists all of the nearby systems. If the user picks one, then the extra column for the DMs will be shown.

https://travellertoolsdemo.azurewebsites.net/world/M1105/-4,-1/2036/trade

**Comment by Grauenwolf** [comment]
The change has been implemented. It should be live in about ten minutes.

https://travellertoolsdemo.azurewebsites.net/world/M1105/-4,-1/2036/trade
