### ISSUE TITLE
Feature request: Disable specific sections of trade calculator output

### ISSUE THREAD

**Issue by adajd** [Grauenwolf/TravellerTools#75]
The trade calculator outputs a lot of information all at once, which can make it difficult to find the specific information needed. 

For example, if I only need the information in the “Trade Preview” section for each world, it would be very helpful to be able to disable the randomly-generated cargos, passengers, etc.

**Comment by Grauenwolf** [comment]
This is being done in Traveller Tools II. You can see a preview of it at https://travellertoolsdemo.azurewebsites.net/
