### ISSUE TITLE
Feature request: Select destination from dropdown menu

### ISSUE THREAD

**Issue by adajd** [Grauenwolf/TravellerTools#76]
If I only need the information for a specific origin and destination, it would be helpful to be able to select the destination world from a dropdown menu like you can already do with the origin world. 

Right now you can only do this by manually inputting the UWPs for both worlds, which is a lot less convenient.

**Comment by Grauenwolf** [comment]
This is covered in Traveller Tools II.

When you pick the 'Travel' tab, you can then select your destination.

https://travellertoolsdemo.azurewebsites.net/world/M1105/-4,-1/2036/travel

As I write this, Freight & Mail is working. Passengers is not ready yet.
