### ISSUE TITLE
Feature request: Average price option (instead of random)

### ISSUE THREAD

**Issue by adajd** [Grauenwolf/TravellerTools#78]
It would be helpful to have a trade calculator option that would display average prices for each trade good rather than random prices. 

That is, instead of generating random numbers, it would simply use the average value for each dice roll (e.g. 10 for a 3d6 roll, or 7 for a 2d6 roll), and output the prices accordingly. 

This could also be a useful option for the available tons for each trade good, in addition to the prices.

**Comment by Grauenwolf** [comment]
Added "Expected Price" column when not rolling for broker score.

The approximation I used was PurchaseDM+Broker (or streetwise) x 5%. This lines up well with the Mongoose 2 charts.
