### ISSUE TITLE
Bug Report: Trade info uses Mongoose 1e trade goods even in Mongoose 2e mode

### ISSUE THREAD

**Issue by adajd** [Grauenwolf/TravellerTools#86]
I just noticed that, in Mongoose 2e mode, the trade good categories don’t quite match up with the ones in the Mongoose 2e rulebook. For example, TravellerTools is showing “Basic Machine Parts” in 2e mode, even though that category only exists in 1e. The closest 2e equivalent would be “Common Industrial Goods”, I think.

**Comment by Grauenwolf** [comment]
Huh, it looks like the MgT2 file is all wrong. I'm going to have to go through it and fix things.

Do you happen to know if they made a 2nd edition for Merchant Prince yet?

**Comment by Grauenwolf** [comment]
Fixed in Traveller Tools II. https://travellertoolsdemo.azurewebsites.net/
