### ISSUE TITLE
data issue with MGT2e trade chart

### ISSUE THREAD

**Issue by Malkleth** [Grauenwolf/TravellerTools#95]
Aside from some names being incorrect, eg, basic machine parts instead of common industrial goods, some of the base prices for these items are incorrect (Common Electronics in the MGT2e book being 20k, your app lists them as 10k)

**Comment by Grauenwolf** [comment]
Thank you for your help. Please verify your changes were deployed correctly.

* http://travellertools.azurewebsites.net/
* https://travellertoolsdemo.azurewebsites.net/

If you're interested in contributing new features, the Blazor branch is where stuff is going.
