### ISSUE TITLE
New to Traveller Tools

### ISSUE THREAD

**Issue by Vayne187** [Grauenwolf/TravellerTools#97]
I love the program but I am honestly perplexed with how the trade function works. I started with Traveller tools and have been experimenting with the Traveller Tools II 

1.  Are we supposed to input our skill ranks only into the Broker/Streetwise Score box or do we add a stat bonus DM as well? I ask because of the differences from version one and version 2. In one it has (INT) next to the corresponding boxes. 

2. When you input the Planet you're on and the planet you're going to, You get available trade goods, you scroll down to get Desired goods. Are those the actual sale prices for the goods purchased after you land one the destination planet or are they the desired goods for the planet you are currently on. Ex. My crew is on Tech World in the Trojan Reach. When I bring up the  the trade info for Tech World heading to Falcon, are the listed available Trade goods and Desired good for only Tech World or are the desired goods the sale price for when you arrive at Falcon. To me that seems that the lists are for available trade to Falcon, while the Desired goods are what Tech world is purchasing. Some of my players are telling me that the desired goods are the prices Falcon is buying the goods from Tech World. I am just trying to clear things up. To me it would make sense that those are all the trade items for Tech World because there are times the Desired Goods far exceeds the goods available, which I would think if they were the sale price of the items you bought then the lists would be the same.

I am told different things by different people so I figured I would come here and ask the source to hopefully get some clarification. 

I think if I can get the answer to these questions I would be good to go which would free up SOOOO much time in my games. 

 PS any time frame when Traveller Tools II will include freight, encounters, mail, and Passengers That truly excites me, when that is done. Great work so far folks!

**Comment by Grauenwolf** [comment]
1. Rules as written, you only get your skill bonus.
2. "Desired Goods" is what you can sell them for where you are at currently. In Tools 1, it would also show you a hint at what you could sell them for in the "Trade preview" section. Tools 2 doesn't have that.
